import {describe,expect,it} from "vitest";
import {classifyOpeningEstimate,evaluate,parseCard,policyImprovement,settle,solveFlop,solveOpening,solveRiver} from "./engine";
import golden from "./evaluator-golden.json";
const cards=(text:string)=>text.split(" ").map(parseCard);
describe("UTH engine",()=>{
  it("orders every Hold'em category and wheel correctly",()=>{const hands=["As Kd 9c 7h 5s 3d 2c","As Ad 9c 7h 5s 3d 2c","As Ad 9c 9h 5s 3d 2c","As Ad Ac 9h 5s 3d 2c","As 2d 3c 4h 5s 9d Tc","As Js 9s 5s 3s Kd 2c","As Ad Ac 9h 9s 3d 2c","As Ad Ac Ah 9s 3d 2c","9s Ts Js Qs Ks 3d 2c"].map(x=>evaluate(cards(x)));expect(hands.map(x=>x[0])).toEqual([0,1,2,3,4,5,6,7,8]);expect(evaluate(cards("As 2d 3c 4h 5s 9d Tc"))[1]).toBe(5);});
  it("settles nonqualification without cancelling Play or Blind",()=>{const p=evaluate(cards("Ts 6d 2c 3d 4h 8s 9c")),d=evaluate(cards("Js 7d 2c 3d 4h 8s 9c"));expect(settle(p,d,1)).toBe(-2);});
  it("does not accept a hidden dealer card and river matches the Python reference",()=>{const state={player:cards("As Qs"),dealerVisible:parseCard("Kh"),board:cards("Js 8s 3c 2d 7h")};const result=solveRiver(state);expect(result.exact).toBe(true);expect(result.outcomes).toBe(44);expect(result.action).toBe("1X");expect(result.evs["1X"]).toBeCloseTo(-.8409090909090909,12);});
  it("matches the Python exact flop reference",()=>{const result=solveFlop({player:cards("As Qs"),dealerVisible:parseCard("Kh"),board:cards("Js 8s 3c")});expect(result.outcomes).toBe(45_540);expect(result.evs["2X"]).toBeCloseTo(2.1409969257795374,12);expect(result.evs.CHECK).toBeCloseTo(1.6757136583223542,12);});
  it("measures information under one conditional state and never reports it as negative",()=>{const player=cards("Jd Kd"),board=cards("Qd 6h Jc 4h 5c"),normal=solveRiver({player,board}),exposed=solveRiver({player,board,dealerVisible:parseCard("Qs")});expect(normal.action).toBe("1X");expect(exposed.action).toBe("FOLD");expect(policyImprovement(exposed,normal)).toBeCloseTo(1,12);});
  it("matches the Python reference evaluator corpus",()=>{for(const item of golden)expect(evaluate(item.cards.map(parseCard))).toEqual(item.rank);});
  it("samples flop information states with exact continuation values",()=>{const result=solveOpening({player:cards("As Qs"),dealerVisible:parseCard("Kh"),board:[]},6);expect(result.method).toBe("PAIRED_STRATIFIED_MONTE_CARLO+EXACT_CHILDREN");expect(result.sampledStates).toBe(6);expect(result.populationStates).toBe(18_424);expect(result.outcomes).toBe(6*45_540);expect(result.status).toContain("INCONCLUSIVE");});
  it("separates confident action selection from numeric EV precision",()=>{expect(classifyOpeningEstimate(.2,.05)).toEqual({confirmed:true,precisionTargetMet:false});expect(classifyOpeningEstimate(.02,.05)).toEqual({confirmed:false,precisionTargetMet:false});expect(classifyOpeningEstimate(.002,.0009)).toEqual({confirmed:true,precisionTargetMet:true});});
});
