"use client";
import {useMemo,useState} from "react";
import {Button,Metric,Panel} from "@/components/ui";
import {parseCard,parseCards,solve} from "@/lib/chaseFlush/engine";

const fmt=(n:number)=>`${n>=0?"+":""}${n.toFixed(6)}`;
export function ChaseFlushLab(){
  const [player,setPlayer]=useState("Ah 8h 4c"),[dealer,setDealer]=useState("Kh"),[board,setBoard]=useState("2h 7s"),[run,setRun]=useState(0);
  const result=useMemo(()=>{void run;try{const p=parseCards(player),b=parseCards(board),v=dealer.trim()?parseCard(dealer):undefined;const informed=solve({player:p,board:b,dealerVisible:v}),normal=solve({player:p,board:b});return{informed,normal,error:""};}catch(e){return{error:e instanceof Error?e.message:String(e)};}},[player,dealer,board,run]);
  return <>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Exact river · sampled backward induction earlier</p><h1 className="mt-2 text-3xl font-semibold">Chase the Flush Lab</h1><p className="mt-2 max-w-3xl text-zinc-400">Analyze optimal 3x / 2x / 1x decisions when exactly one dealer card is exposed. The engine never receives the dealer’s two hidden cards.</p></div><a className="text-sm text-emerald-400 hover:underline" href="https://wizardofodds.com/games/chase-the-flush/" target="_blank" rel="noreferrer">Rules source ↗</a></div>
    <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Exposed EV / Ante" value="+12.2279%" sub="95% CI +12.0291% to +12.4266%"/><Metric label="Information value" value="+8.6442%" sub="paired CI +8.6080% to +8.6804%"/><Metric label="Edge / initial 2 units" value="+6.1140%" sub="full exposed strategy"/><Metric label="Edge / total action" value="+3.4665%" sub="average wager 3.527184"/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
      <Panel><h2 className="text-lg font-semibold">Hand analyzer</h2><p className="mt-1 text-sm text-zinc-500">Enter 0, 2, or 4 community cards. Suits: c d h s.</p><div className="mt-5 grid gap-4">
        {[{label:"Player cards",value:player,set:setPlayer,placeholder:"Ah 8h 4c"},{label:"Exposed dealer card",value:dealer,set:setDealer,placeholder:"Kh"},{label:"Community cards",value:board,set:setBoard,placeholder:"2h 7s"}].map(x=><label key={x.label} className="grid gap-2 text-sm text-zinc-400">{x.label}<input className="field rounded-xl px-4 py-3 text-zinc-100 outline-none" value={x.value} placeholder={x.placeholder} onChange={e=>x.set(e.target.value)}/></label>)}
      </div><Button className="mt-5" onClick={()=>setRun(x=>x+1)}>Calculate optimal action</Button></Panel>
      <Panel>{result.error?<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{result.error}</div>:result.informed&&result.normal?<><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Optimal decision</p><div className="mt-3 text-4xl font-semibold text-emerald-300">{result.informed.action.toUpperCase()}</div><div className="mt-5 space-y-3">{Object.entries(result.informed.evs).map(([a,v])=><div key={a} className="flex justify-between rounded-xl bg-black/20 p-3"><span>{a.toUpperCase()}</span><b className={v>=0?"text-emerald-300":"text-red-300"}>{fmt(v)}</b></div>)}</div><div className="mt-5 border-t border-white/[.07] pt-4 text-sm text-zinc-400"><p>Decision margin: <b className="text-white">{result.informed.difference.toFixed(6)} units</b></p><p className="mt-2">Without dealer information: <b className="text-white">{result.normal.action.toUpperCase()}</b> ({fmt(Math.max(...Object.values(result.normal.evs)))})</p><p className="mt-2 text-xs text-zinc-500">{result.informed.exact?"Exact enumeration of every legal hidden dealer hand.":"Reproducible sampled backward induction; exact solver available in the Python package."}</p></div></>:null}</Panel>
    </div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel><h2 className="font-semibold">Rules modeled</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-zinc-400"><li>Three player cards, three dealer cards, then community cards 2 + 2.</li><li>Check or 3x; check or 2x; finally 1x or fold.</li><li>Dealer qualifies with at least a 9-high three-card flush.</li><li>Non-qualifying dealer pushes Ante before comparison.</li><li>X‑Tra: 4 / 5 / 6 / 7-card flush pays 1 / 5 / 50 / 250 to 1.</li></ul></Panel><Panel><h2 className="font-semibold">20-million-hand result</h2><p className="mt-4 text-sm leading-6 text-zinc-400">Policies were trained backward on two million independent legal deals per decision policy, then evaluated on 20 million new paired deals. A separate legacy-paytable run reproduced Wizard’s published −2.3907% EV within 0.0524 percentage points.</p><div className="mt-4 rounded-xl border border-amber-400/20 bg-amber-400/[.07] p-3 text-xs leading-5 text-amber-200">Wizard’s displayed paytable says 50:1 for six cards, but its analysis rows use 20:1. Results here use the displayed current 50:1 rule; under it, even uninformed optimal play is estimated at +3.5836% per Ante.</div></Panel></div>
    <Panel className="mt-5"><h2 className="font-semibold">Where the information value appears</h2><div className="mt-4 grid gap-3 sm:grid-cols-4 text-sm">{[["Baseline","+0.035836"],["Final-card access","+0.053926"],["Added at 2x stage","+0.020048"],["Added at 3x stage","+0.012469"]].map(([k,v])=><div className="rounded-xl bg-black/20 p-3" key={k}><p className="text-zinc-500">{k}</p><b className="mt-1 block text-emerald-300">{v}</b></div>)}</div></Panel>
  </>;
}
