"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Button,GhostButton,Metric,Panel,Select} from "@/components/ui";
import {cardName,parseCard,RANKS,SUITS,type UTHDecision} from "@/lib/uth/engine";

type Tab="strategy"|"analyzer"|"exposed"|"simulation"|"deviations";
type Stage=0|3|5;
type Target="player"|"dealer"|"board";
type Result={exposed:UTHDecision;normal:UTHDecision;informationValue:number|null;actionChanged:boolean|null};
const glyph:Record<string,string>={c:"♣",d:"♦",h:"♥",s:"♠"};
const label=(card:number)=>{const text=cardName(card);return`${text[0]==="T"?"10":text[0]}${glyph[text[1]]}`;};
const fmt=(n:number|null)=>n===null?"PENDING":!Number.isFinite(n)?"N/A":`${n>=0?"+":""}${n.toFixed(4)}`;

function CardBox({title,cards,onClick,active,onActivate,empty}:{title:string;cards:number[];onClick:(c:number)=>void;active:boolean;onActivate:()=>void;empty:string}){
  return <button type="button" onClick={onActivate} className={`min-h-28 rounded-xl border p-3 text-left ${active?"border-emerald-400/70 bg-emerald-500/10":"border-white/10 bg-black/15"}`}><span className="text-xs font-bold uppercase tracking-wider text-zinc-500">{title}</span><div className="mt-3 flex flex-wrap gap-2">{cards.length?cards.map(card=><span key={card} onClick={event=>{event.stopPropagation();onClick(card);}} className={`rounded-lg bg-white px-3 py-2 font-bold ${["d","h"].includes(cardName(card)[1])?"text-red-600":"text-zinc-950"}`}>{label(card)} ×</span>):<span className="text-sm text-zinc-600">{empty}</span>}</div></button>;
}

export function UTHLab(){
  const[tab,setTab]=useState<Tab>("analyzer"),[stage,setStage]=useState<Stage>(5),[target,setTarget]=useState<Target>("player"),[exposed,setExposed]=useState(true),[player,setPlayer]=useState(()=>[parseCard("As"),parseCard("Qs")]),[dealer,setDealer]=useState(()=>[parseCard("Kh")]),[board,setBoard]=useState(()=>[parseCard("Js"),parseCard("8s"),parseCard("3c"),parseCard("2d"),parseCard("7h")]),[result,setResult]=useState<Result>(),[error,setError]=useState(""),[loading,setLoading]=useState(false),[samples,setSamples]=useState(24),[ante,setAnte]=useState(25),[rounds,setRounds]=useState(40);
  const worker=useRef<Worker|null>(null),request=useRef(0),selected=useMemo(()=>new Set([...player,...dealer,...board]),[player,dealer,board]);
  useEffect(()=>{const instance=new Worker(new URL("../workers/uth.worker.ts",import.meta.url));worker.current=instance;instance.onmessage=(event:MessageEvent<Result&{id:number;error?:string}>)=>{if(event.data.id!==request.current)return;setLoading(false);if(event.data.error)setError(event.data.error);else setResult(event.data);};return()=>instance.terminate();},[]);
  const clear=()=>{setResult(undefined);setError("");};
  const changeStage=(value:Stage)=>{setStage(value);setBoard(cards=>cards.slice(0,value));setTarget("board");clear();};
  const remove=(card:number)=>{setPlayer(x=>x.filter(c=>c!==card));setDealer(x=>x.filter(c=>c!==card));setBoard(x=>x.filter(c=>c!==card));clear();};
  const add=(card:number)=>{if(selected.has(card))return;if(target==="player"&&player.length<2)setPlayer(x=>[...x,card]);if(target==="dealer")setDealer([card]);if(target==="board"&&board.length<stage)setBoard(x=>[...x,card]);clear();};
  const randomize=()=>{const cards=Array.from({length:52},(_,i)=>i);for(let i=51;i;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}setPlayer(cards.slice(0,2));setDealer(cards.slice(2,3));setBoard(cards.slice(3,3+stage));clear();};
  const analyze=()=>{if(player.length!==2)return setError("Select exactly two player cards.");if(board.length!==stage)return setError(`Select exactly ${stage} community cards.`);if(exposed&&dealer.length!==1)return setError("Select exactly one exposed dealer card.");setLoading(true);setError("");setResult(undefined);worker.current?.postMessage({id:++request.current,state:{player,board,...(exposed?{dealerVisible:dealer[0]}:{})},samples});};
  return <>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Exact late-stage EV and exposed-card research</p><h1 className="mt-2 text-3xl font-semibold">Ultimate Texas Hold&apos;em</h1><p className="mt-2 max-w-3xl text-zinc-400">Analyze standard UTH or condition every legal decision on exactly one exposed dealer card—never the hidden card.</p></div><a className="min-h-11 text-sm text-emerald-400 hover:underline" href="https://wizardofodds.com/games/ultimate-texas-hold-em/" target="_blank" rel="noreferrer">Wizard rules source ↗</a></div>
    <div className="mt-6 flex flex-wrap gap-2" role="tablist">{(["strategy","analyzer","exposed","simulation","deviations"] as Tab[]).map(item=><GhostButton key={item} role="tab" aria-selected={tab===item} onClick={()=>setTab(item)} className={tab===item?"border-emerald-400/60 bg-emerald-500/15":""}>{item==="strategy"?"Basic Strategy":item==="exposed"?"Dealer Card Exposed":item[0].toUpperCase()+item.slice(1)}</GhostButton>)}</div>
    {tab==="strategy"?<Strategy/>:tab==="simulation"?<Simulation ante={ante} setAnte={setAnte} rounds={rounds} setRounds={setRounds}/>:tab==="deviations"?<Deviations result={result}/>:tab==="exposed"?<ExposedResearch/>:<>
      <Panel className="mt-5"><div className="grid gap-4 md:grid-cols-3"><Select label="Decision stage" value={stage} onChange={e=>changeStage(Number(e.target.value) as Stage)}><option value={0}>Opening 4X</option><option value={3}>After flop 2X</option><option value={5}>River 1X</option></Select><Select label="Dealer information" value={exposed?"one":"none"} onChange={e=>{setExposed(e.target.value==="one");clear();}}><option value="none">None</option><option value="one">One card exposed</option></Select><Select label="Opening flop states" value={samples} onChange={e=>setSamples(Number(e.target.value))}><option value={12}>12 · faster</option><option value={24}>24 · balanced</option><option value={64}>64 · higher precision</option></Select></div><p className="mt-4 text-xs leading-5 text-zinc-500">River and flop are exact. Opening samples stratified flop states without replacement, solves every sampled continuation exactly, and applies a finite-population correction. It is confirmed only when the paired 99.9% interval excludes zero with ≤0.001 Ante-unit half-width.</p></Panel>
      <div className="mt-4 grid gap-3 md:grid-cols-3"><CardBox title="Player cards" cards={player} onClick={remove} active={target==="player"} onActivate={()=>setTarget("player")} empty="Choose 2 cards"/><CardBox title="Exposed dealer card" cards={exposed?dealer:[]} onClick={remove} active={target==="dealer"&&exposed} onActivate={()=>exposed&&setTarget("dealer")} empty={exposed?"Choose exactly 1":"No dealer information"}/><CardBox title="Community cards" cards={board} onClick={remove} active={target==="board"} onActivate={()=>setTarget("board")} empty={stage?`Choose ${stage} cards`:"No board at opening"}/></div>
      <Panel className="mt-4"><div className="grid grid-cols-4 gap-2 sm:grid-cols-13">{[...SUITS].flatMap(s=>[...RANKS].map(r=>{const card=parseCard(r+s),disabled=selected.has(card);return<button type="button" disabled={disabled} onClick={()=>add(card)} key={card} className={`min-h-11 rounded-lg border border-white/10 bg-white px-1 font-bold disabled:opacity-20 ${["d","h"].includes(s)?"text-red-600":"text-zinc-950"}`}>{r==="T"?"10":r}{glyph[s]}</button>;}))}</div><div className="mt-4 flex flex-wrap gap-2"><Button data-enter-action="true" onClick={analyze} disabled={loading}>{loading?"Enumerating…":"Calculate EV"}</Button><GhostButton onClick={randomize}>Random hand</GhostButton></div>{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}</Panel>
      {result&&<ResultPanel result={result} informed={exposed}/>}</>}
  </>;
}

function ResultPanel({result,informed}:{result:Result;informed:boolean}){const shown=informed?result.exposed:result.normal,stateCount=shown.sampledStates===undefined?"":` · ${shown.sampledStates.toLocaleString()}/${shown.populationStates?.toLocaleString()} flop states`;return <div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel className="border-emerald-400/20"><p className="text-xs font-bold uppercase tracking-wider text-emerald-400">Recommended decision</p><h2 className="mt-2 text-3xl font-bold">{shown.action}</h2>{Object.keys(shown.evs).length>0&&<div className="mt-5 grid grid-cols-2 gap-3">{Object.entries(shown.evs).map(([action,ev])=><Metric key={action} label={`${action} EV`} value={fmt(ev)}/>)}</div>}<p className="mt-4 text-sm text-zinc-400">{shown.decisionMarginAvailable!==false&&<>Difference {fmt(shown.difference)} · </>}{shown.method}{shown.outcomes>0&&<> · {shown.outcomes.toLocaleString()} terminal outcomes{stateCount}</>}</p>{shown.method==="PUBLISHED_OPTIMAL_STRATEGY"&&<p className="mt-2 text-sm text-zinc-500">The standard opening action comes from the published optimal 4X/check chart; no numeric margin is inferred.</p>}{shown.method.includes("MONTE_CARLO")&&<p className="mt-2 text-sm text-amber-300">99.9% paired delta CI [{fmt(shown.confidenceInterval[0])}, {fmt(shown.confidenceInterval[1])}] · SE {Number.isFinite(shown.standardError)?shown.standardError.toFixed(5):"not estimable"}</p>}</Panel><Panel><h2 className="font-semibold">Information effect</h2><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Normal action" value={result.normal.action}/><Metric label="Exposed action" value={result.exposed.action}/><Metric label="Action changed" value={result.actionChanged===null?"PENDING":result.actionChanged?"YES":"NO"}/><Metric label="Policy improvement" value={fmt(result.informationValue)}/></div><p className="mt-4 text-xs leading-5 text-zinc-500">Policy improvement is measured under the exposed state: its best EV minus the EV of the confirmed normal-policy action. It is withheld when the exposed opening recommendation is inconclusive. The hidden dealer card is always integrated out.</p></Panel></div>}

function Strategy(){return <div className="mt-5 grid gap-4 lg:grid-cols-2"><Panel><h2 className="text-xl font-semibold">Opening · 4X or check</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Raise all pairs except deuces. Suited: A-any, K-any, Q6+, J8+. Unsuited: A-any, K5+, Q8+, JT. Check everything else.</p><p className="mt-3 text-xs text-zinc-500">Wizard advanced Decision Point 1. Standard rules permit 3X, but the optimal chart uses 4X; this module follows the requested 4X-only interface.</p></Panel><Panel><h2 className="text-xl font-semibold">Flop · 2X or check</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Simple chart: raise two pair or better; a hidden pair except pocket deuces; or four to a flush containing a hidden ten or better. Exact analyzer recommendations use backward induction, not this shortcut.</p></Panel><Panel><h2 className="text-xl font-semibold">River · 1X or fold</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Simple chart: raise a hidden pair or better, or with fewer than 21 single-card dealer outs. The exact analyzer enumerates complete two-card holdings, which the shortcut deliberately omits.</p></Panel><Panel><h2 className="text-xl font-semibold">Qualification and Blind</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Dealer opens with a pair or better. If not, Ante pushes; Play and Blind still resolve. Ties push. Blind wins: royal 500, straight flush 50, quads 10, full house 3, flush 1.5, straight 1; lower hands push.</p><p className="mt-3 text-xs text-zinc-500">Wizard optimal baseline: −0.02185/Ante, average total wager 4.152252, element of risk 0.526%, SD 4.94. Wizard simple strategy: about 2.43% house edge.</p></Panel></div>}

function ExposedResearch(){return <div className="mt-5 grid gap-4 md:grid-cols-2"><Panel><h2 className="text-xl font-semibold">Information schedule</h2><p className="mt-3 text-sm leading-6 text-zinc-400">The research runner supports baseline, river-only reveal, reveal from flop, and reveal from the opening. Each policy receives a freshly constructed information state at each decision.</p><pre className="mt-4 overflow-x-auto rounded-lg bg-black/30 p-3 text-xs text-emerald-300">python uth_simulate.py --mode stages --hands 100000</pre></Panel><Panel><h2 className="text-xl font-semibold">No edge assumed</h2><p className="mt-3 text-sm leading-6 text-zinc-400">An exposed dealer card changes both card-removal probabilities and available decisions. Results are withheld until the ordinary optimal game validates and paired uncertainty meets the quality target.</p><p className="mt-3 text-xs text-amber-300">Current repository artifacts are research outputs, not a claim that exposed-card UTH is positive.</p></Panel></div>}

function Simulation({ante,setAnte,rounds,setRounds}:{ante:number;setAnte:(n:number)=>void;rounds:number;setRounds:(n:number)=>void}){const ev=-.02185,sd=4.94;return <><div className="mt-5 grid gap-4 md:grid-cols-3"><Panel><label className="text-xs text-zinc-500">Ante dollars<input className="mt-2 w-full rounded-lg bg-black/25 p-3 text-white" type="number" min="1" value={ante} onChange={e=>setAnte(Number(e.target.value))}/></label></Panel><Panel><label className="text-xs text-zinc-500">Rounds / hour<input className="mt-2 w-full rounded-lg bg-black/25 p-3 text-white" type="number" min="1" value={rounds} onChange={e=>setRounds(Number(e.target.value))}/></label></Panel><Panel><p className="text-xs text-zinc-500">Published optimal baseline</p><p className="mt-2 text-2xl font-semibold">{(ev*ante*rounds).toLocaleString(undefined,{style:"currency",currency:"USD"})}/hr</p><p className="mt-2 text-xs text-zinc-500">SD/hour ≈ {(sd*ante*Math.sqrt(rounds)).toLocaleString(undefined,{style:"currency",currency:"USD"})}; normal approximation.</p></Panel></div><Panel className="mt-4"><h2 className="text-xl font-semibold">Run reproducible research</h2><pre className="mt-4 overflow-x-auto rounded-lg bg-black/30 p-3 text-xs text-emerald-300">{`python uth_validate.py --hands 100000000\npython uth_simulate.py --mode paired --hands 100000000 --workers auto\npython benchmark.py --workers auto`}</pre><p className="mt-3 text-sm text-zinc-400">JSON exports include EV, SD, variance, N0 when EV is positive, action frequencies, average Play and total action, paired confidence intervals, paytable, seed, runtime, solver version, and Git commit.</p></Panel></>}

function Deviations({result}:{result?:Result}){return <div className="mt-5 grid gap-4 md:grid-cols-2"><Panel><h2 className="text-xl font-semibold">Strategy-change extraction</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Exact river and flop states where the exposed card flips the decision can be exported with both EV margins and information value.</p><pre className="mt-4 overflow-x-auto rounded-lg bg-black/30 p-3 text-xs text-emerald-300">python uth_extract_strategy.py --stage river --states 10000</pre></Panel><Panel><h2 className="text-xl font-semibold">Current analyzed state</h2>{result?<div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Normal" value={result.normal.action}/><Metric label="Exposed" value={result.exposed.action}/><Metric label="Changed" value={result.actionChanged?"YES":"NO"}/><Metric label="Value" value={fmt(result.informationValue)}/></div>:<p className="mt-3 text-sm text-zinc-500">Analyze a hand first to inspect its deviation.</p>}<p className="mt-4 text-xs text-zinc-500">Human-readable exposed rules must be learned from exported solver data and validated out-of-sample; none are invented here.</p></Panel></div>}
