"""Export the audited JSON aggregates to the CountLab TypeScript bundle."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


HEADER = '''// Generated by ../blackjack-simulator/export_typescript.py.
// Do not edit these coefficients by hand; regenerate them from the audited JSON.
export type RawCoefficient = readonly [
  frequency: number,
  advantage: number,
  standardDeviation: number,
  samples: number,
  standardError: number,
];
export const GAME_OPTIONS = {
  6: [
    { dealt: 4, label: "4 / 6 decks" },
    { dealt: 4.5, label: "4.5 / 6 decks" },
    { dealt: 4.75, label: "4.75 / 6 decks" },
    { dealt: 5, label: "5 / 6 decks" },
    { dealt: 5.25, label: "5.25 / 6 decks" },
  ],
  8: [
    { dealt: 5.5, label: "5.5 / 8 decks" },
    { dealt: 6, label: "6 / 8 decks" },
    { dealt: 6.5, label: "6.5 / 8 decks" },
    { dealt: 7, label: "7 / 8 decks" },
  ],
} as const;
'''


def number(value: float) -> str:
    return format(value, ".12g")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("artifact", type=Path)
    parser.add_argument("--typescript", type=Path, required=True)
    parser.add_argument("--public-json", type=Path)
    args = parser.parse_args()
    payload = json.loads(args.artifact.read_text(encoding="utf-8"))

    total_rounds = sum(profile["rounds"] for profile in payload["profiles"].values())
    metadata = payload["metadata"]
    lines = [HEADER]
    lines.extend([
        "export const COEFFICIENT_METADATA = {",
        f'  generatedUtc: "{metadata["created_utc"]}",',
        f'  sourceSha256: "{metadata["source_sha256"]}",',
        f'  seed: {metadata["seed"]},',
        f'  shoesPerProfile: {metadata["requested_shoes_per_configuration"]},',
        f"  totalRounds: {total_rounds},",
        '  model: "6/8 deck | H17 | DAS | RSA | LS | peek | 3:2 | one spot | split to 4 hands",',
        '  trueCount: "floored using exact undealt cards; updated before playing decisions",',
        '  dataUrl: "/blackjack/data/blackjack-coefficients.json",',
        "} as const;",
        "export const RAW_COEFFICIENTS: Record<string, readonly RawCoefficient[]> = {",
    ])
    for key, profile in payload["profiles"].items():
        lines.append(f'  "{key}": [')
        for row in profile["rows"]:
            lines.append(
                "    ["
                + ", ".join((
                    number(row["frequency"]),
                    number(row["advantage"]),
                    number(row["standard_deviation"]),
                    str(row["rounds"]),
                    number(row["standard_error"]),
                ))
                + "],"
            )
        lines.append("  ],")
    lines.append("};")
    lines.append("")
    args.typescript.parent.mkdir(parents=True, exist_ok=True)
    args.typescript.write_text("\n".join(lines), encoding="utf-8")
    if args.public_json:
        args.public_json.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(args.artifact, args.public_json)


if __name__ == "__main__":
    main()
